### PR TITLE
Add carrot-rcc

### PR DESCRIPTION
**Pull request by datakurre**
And did also iterate formatting and wording; I removed bold from ingress

### CODE REVIEW

**Comment by celanthe** [comment]
[Needs Review: Pull Requests in Robot Framework Repository](https://trello.com/c/32yTJFTJ/984-needs-review-pull-requests-in-robot-framework-repository)

**Comment by celanthe** [comment]
Hi @datakurre! Thank you so much for the pull request. Would you be so kind as to resolve the conflicts on this branch so that @Nlea can review this PR and get it merged? 

Thank you again for your contribution! :)

**Comment by datakurre** [comment]
Aww... I missed pending pull from Markus with a lot of similar changes. This would require almost a rewrite, so I will return later.

**Comment by Nlea** [comment]
@datakurre no worries. Thanks for the contribution. We have to include carrot here as well :)

**Pull request closed without merging**
